name: Lighthouse CI

on:
  push:
    branches:
      - main
      - work
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      TAILWIND_DISABLE_OXIDE: '1'
      LIGHTHOUSE_OUTPUT_DIR: docs/lighthouse/reports

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (no optional, JS fallback for Tailwind)
        run: npm ci --omit=optional

      - name: Build
        run: npm run build

      - name: Start server
        run: |
          npm run start -- --hostname 0.0.0.0 &
          npx wait-on http://127.0.0.1:3000

      - name: Run Lighthouse audits
        env:
          LIGHTHOUSE_URL: http://127.0.0.1:3000
        run: npm run audit:all

      - name: Generate Lighthouse summary
        run: node scripts/generate-lighthouse-summary.js

      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            docs/lighthouse/reports/*.json
            docs/lighthouse/summary.json

      - name: Stop server
        if: always()
        run: |
          pkill -f "next start" || true
